services:
  bookify.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=${HTTPPORT}
      - ASPNETCORE_URLS=${URL}
      - ConnectionStrings:Database=${POSTGRESSQL}
      - ConnectionStrings:Cache=${REDIS_CONN_STRING}
      - Authentication:Audience=${AUDIENCE}
      - Authentication:ValidIssuer=${ISSUER}
      - Authentication:MetadataUrl=${METADATAURL}
      - Authentication:RequireHttpsMetadata=${REQUIREHTTPSMETADATA}
      - Keycloak:BaseUrl=${KEYCLOAKBASEURL}
      - Keycloak:AdminUrl=${KEYCLOAKADMINURL}
      - Keycloak:TokenUrl=${KEYCLOAKTOKENURL}
      - Keycloak:AdminClientId=${KEYCLOAKADMINCLIENTID}
      - Keycloak:AdminClientSecret=${KEYCLOAKADMINCLIENTSECRET}
      - Keycloak:AuthClientId=${KEYCLOAKAUTHCLIENTID}
      - Keycloak:AuthClientSecret=${KEYCLOAKAUTHCLIENTSECRET}
      - Serilog:WriteTo:1:Name=${SEQ_SERVER_NAME}
      - Serilog:WriteTo:1:Args:serverUrl=${SEQ_SERVER_URL}
      - Serilog:Enrich:1=${SEQ_SERVER_ENRICH}
    ports:
      - "5092:80"